DATA:
  shot: 1
  train_ratio: 1.
  data_path: "/raid/candi/yiwen/data/multiorgan_final"
  fold: 1
  resolution: [ 0.75, 0.75, 2.5 ]  # [1.25, 1.25, 2.5]
  size: [ 256, 256, 40 ]  # [256, 256, 96]
  novel_ins: 3

MODEL:
  model: "baseline_2d"
  feature: 32 # 32
  seg_loss: "dice"
  alpha: 0.125
  align: False
